name: clash-pong
version: 0.1.0
category: hardware, game

custom-setup:
  dependencies:
    - base
    - Cabal
    - clashilator
    
dependencies:
  - base
  - clash-prelude
  - clash-lib
  - clash-ghc
  - retroclash-lib
  - retroclash-sim

  - clash-shake
  
  - lens
  - mtl
  - sdl2
  - text
  - array
  - monad-loops

default-extensions:
  - DataKinds
  - TypeFamilies
  - FlexibleContexts
  - TemplateHaskell
  - DeriveGeneric
  - DeriveAnyClass
  - NoStarIsType
  - TypeOperators

source-dirs:
  - src

flags:
  verilator:
    manual: True
    default: False

executables:
  pong:
    main: simulator.hs

  pong-verilator:
    main: verilator.hs
    when:
    - condition: flag(verilator)
      then:
        verbatim:
          x-clashilator-top-is: Pong
      else:
        buildable: false
