name: clash-pong
version: 0.1.0
category: hardware, game

dependencies:
  - base
  - clash-prelude
  - clash-lib
  - clash-ghc
  - retroclash-lib
  - retroclash-sim

  - shake == 0.17.9
  - mustache == 2.3.1
  - lens
  - mtl
  - sdl2
  - text

default-extensions:
  - DataKinds
  - TypeFamilies
  - FlexibleContexts
  - TemplateHaskell
  - DeriveGeneric
  - DeriveAnyClass
  - NoStarIsType
  - TypeOperators

source-dirs:
  - src
  
executables:
  pong:
    main: Simulator.hs
    
