name: clash-pong
version: 0.1.0
category: hardware, game

dependencies:
  - base
  - clash-prelude
  - clash-lib
  - clash-ghc
  - shake == 0.17.9
  - mustache == 2.3.1
  - retroclash-lib
  - lens
  - mtl
  - sdl2
  - text

default-extensions:
  - DataKinds
  - TypeFamilies
  - FlexibleContexts
  - TemplateHaskell
  - DeriveGeneric
  - DeriveAnyClass

source-dirs:
  - src-clash
  - src-sim
  
executables:
  pong:
    main: Main.hs
    
