name: clash-pong
version: 0.1.0
category: hardware, game

dependencies:
  - base
  - clash-prelude
  - clash-lib
  - clash-ghc
  - retroclash-lib
  - retroclash-sim

  - shake
  - mustache == 2.3.1
  - lens
  - mtl
  - sdl2
  - text
  - array
  - monad-loops

default-extensions:
  - DataKinds
  - TypeFamilies
  - FlexibleContexts
  - TemplateHaskell
  - DeriveGeneric
  - DeriveAnyClass
  - NoStarIsType
  - TypeOperators

source-dirs:
  - src

flags:
  verilator:
    manual: True
    default: False

executables:
  pong:
    main: simulator.hs

  pong-verilator:
    main: verilator.hs
    when:
    - condition: flag(verilator)
      then:
        source-dirs:
          - src
          - verilator
        extra-libraries: stdc++ 
        extra-lib-dirs: verilator
        ghc-options: -O3 -fPIC -pgml g++ -optl-Wl,--allow-multiple-definition -optl-Wl,--whole-archive -optl-Wl,-Bstatic -optl-Wl,-L_build/verilator -optl-Wl,-lVerilatorFFI -optl-Wl,-Bdynamic -optl-Wl,--no-whole-archive
        
        build-tools: hsc2hs
        include-dirs: verilator
      else:
        buildable: false
